version: "2"

services:
    db:
        image: mongo
        container_name: "mongodb"
        
        ports:
            - "27018:27017"
    web:
        build: .
        command: python3 ml/src/main.py
        ports:
            - "5555:5555"
        depends_on: 
            - db

        network_mode: "host"